version: "3"

services:
  zk:
    network_mode: host
    image: zookeeper:3.4

  mesos-master:
    network_mode: host
    image: mesosphere/mesos-master:1.2.0
    entrypoint:
      - mesos-master
    environment:
      - MESOS_IP=127.0.0.1
      - MESOS_CLUSTER=local
      - MESOS_HOSTNAME=mesos-master
      - MESOS_QUORUM=1
      - MESOS_PORT=5050
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_ZK=zk://localhost:2181/mesos

  mesos-slave:
    network_mode: host
    image: mesosphere/mesos-slave:1.2.0
    entrypoint:
      - mesos-slave
    environment:
      - MESOS_CONTAINERIZERS=mesos,docker
      - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      - MESOS_ISOLATION=cgroups/cpu,cgroups/mem,docker/runtime
      - MESOS_MASTER=zk://localhost:2181/mesos
      - MESOS_PORT=5051
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_RESOURCES=ports(*):[11000-11999]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  marathon:
    network_mode: host
    image: mesosphere/marathon:latest
    environment:
      - MARATHON_ZK=zk://localhost:2181/marathon
      - MARATHON_MASTER=zk://localhost:2181/mesos

